version: "3.7"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3326:3306"
    volumes:
      - ./config/mysql/mysql.cnf
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      TZ: 'Asia/Hong_Kong'

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_USERNAME: admin
      MONGO_INITDB_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/mongo:/data/db